# Generated by Django 3.0.7 on 2020-07-03 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_story_storycategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storycategory',
            options={'verbose_name_plural': 'Story Categories'},
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.StoryCategory', verbose_name='Story Category'),
        ),
    ]
