# Generated by Django 3.0.7 on 2020-07-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200709_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='imp',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
