# Generated by Django 3.0.7 on 2020-07-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200709_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglist',
            name='date',
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='status',
            field=models.IntegerField(),
        ),
    ]
