# Generated by Django 3.0.7 on 2020-07-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200710_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='link',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
    ]
