# Generated by Django 3.0.8 on 2020-07-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='imp',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
